### ISSUE TITLE
failed to execute command `gulp` on samples/angular_contacts

### ISSUE THREAD

**Issue by thaihau** [OpenNTF/Script-Portlet-Node-Samples#1]
I am having error when running `gulp` command. Look like the pre-requisite is to install the `sp` command? 

``` javascript
[10:58:22] Error in plugin 'gulp-shell'
Message:
    Command `sp push -mainHtmlFile release/index.html` failed with exit code 127
Error running task sequence: { [Error: Command `sp push -mainHtmlFile release/index.html` failed with exit code 127]
  message: 'Command `sp push -mainHtmlFile release/index.html` failed with exit code 127',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-shell',
  __safety: { toString: [Function] } }
```

**Comment by jbooth1** [comment]
Hi,

Yes, that's correct. The default gulp task defined in gulpfile.js invokes sp push so that the application is pushed to the server.  The Script Portlet command line client support must be installed on your workstation for this functionality

This article has more information about this set of samples: https://developer.ibm.com/digexp/docs/docs/script-portlet/using-node-js-build-tools-with-script-portlet/
